//! Synthetic contract fixtures, not recordings of a live GitHub session.
//! These tests do not contact GitHub, keyrings, or the OS notification service.
use hush::{api::validate_scopes,filter,model::{Config,Event,Kind,Repo,ThreadTask},storage::{Paths,Store}};
use chrono::{Duration,Utc};
use serde_json::{Value,json};
use std::collections::HashSet;

fn repo()->Repo{Repo::parse("atelier/web").unwrap()}
fn since()->chrono::DateTime<Utc>{Utc::now()-Duration::hours(1)}
fn comment(body:&str)->Value{json!({"id":17,"body":body,"user":{"login":"mara"},"created_at":Utc::now().to_rfc3339(),"updated_at":Utc::now().to_rfc3339(),"html_url":"https://github.com/atelier/web/issues/1#issuecomment-17"})}
fn review()->Value{json!({"id":27,"body":"Looks good!","state":"APPROVED","user":{"login":"mara"},"submitted_at":Utc::now().to_rfc3339(),"html_url":"https://github.com/atelier/web/pull/1#pullrequestreview-27"})}
fn request(action:&str)->Value{json!({"id":37,"event":action,"actor":{"login":"mara"},"created_at":Utc::now().to_rfc3339()})}
fn request_event(v:&Value,teams:&HashSet<String>)->Option<Event>{filter::request(v,&repo(),"PR","https://github.com/atelier/web/pull/1","alex",teams,since())}
#[test]fn direct_assignment(){let mut v=request("assigned");v["assignee"]=json!({"login":"alex"});assert!(request_event(&v,&HashSet::new()).is_some());v["assignee"]["login"]=json!("mara");assert!(request_event(&v,&HashSet::new()).is_none());}
#[test]fn direct_review_request(){let mut v=request("review_requested");v["requested_reviewer"]=json!({"login":"ALEX"});assert!(request_event(&v,&HashSet::new()).is_some());}
#[test]fn team_review_request(){let mut v=request("review_requested");v["requested_team"]=json!({"slug":"frontend"});let teams=HashSet::from(["atelier/frontend".into()]);assert!(request_event(&v,&teams).is_some());assert!(request_event(&v,&HashSet::from(["other/frontend".into()])).is_none());}
#[test]fn team_in_polymorphic_reviewer(){let mut v=request("review_requested");v["requested_reviewer"]=json!({"type":"Team","slug":"frontend"});assert!(request_event(&v,&HashSet::from(["atelier/frontend".into()])).is_some());}
#[test]fn removed_request_is_not_new(){let mut v=request("review_request_removed");v["requested_reviewer"]=json!({"login":"alex"});assert!(request_event(&v,&HashSet::new()).is_none());}
#[test]fn request_time_gate(){let mut v=request("assigned");v["assignee"]=json!({"login":"alex"});v["created_at"]=json!((Utc::now()-Duration::days(2)).to_rfc3339());assert!(request_event(&v,&HashSet::new()).is_none());}
#[test]fn issue_open_not_pr_or_update(){let mut v=json!({"id":47,"title":"New issue","body":"Body","user":{"login":"sam"},"created_at":Utc::now().to_rfc3339(),"html_url":"https://github.com/atelier/web/issues/4"});assert_eq!(filter::new_issue(&v,&repo(),since()).unwrap().kind,Kind::Issue);v["pull_request"]=json!({"url":"https://api.github.com/repos/atelier/web/pulls/4"});assert!(filter::new_issue(&v,&repo(),since()).is_none());v.as_object_mut().unwrap().remove("pull_request");v["created_at"]=json!((Utc::now()-Duration::days(20)).to_rfc3339());v["updated_at"]=json!(Utc::now().to_rfc3339());assert!(filter::new_issue(&v,&repo(),since()).is_none());}
#[test]fn review_only_on_my_pr(){assert!(filter::review(&review(),&repo(),"PR","alex","alex",since()).is_some());assert!(filter::review(&review(),&repo(),"PR","someone","alex",since()).is_none());}
#[test]fn all_submitted_review_states(){for state in ["APPROVED","CHANGES_REQUESTED","COMMENTED"]{let mut r=review();r["state"]=json!(state);assert!(filter::review(&r,&repo(),"PR","alex","alex",since()).is_some());}}
#[test]fn pending_dismissed_self_review_do_not_alert(){for state in ["PENDING","DISMISSED"]{let mut r=review();r["state"]=json!(state);assert!(filter::review(&r,&repo(),"PR","alex","alex",since()).is_none());}let mut r=review();r["user"]["login"]=json!("alex");assert!(filter::review(&r,&repo(),"PR","alex","alex",since()).is_none());}
#[test]fn exact_comment_mention(){assert!(filter::comment_mention(&comment("Hey @alex!"),"issue-comment",&repo(),"Issue","alex",since()).is_some());assert!(filter::comment_mention(&comment("Hey @alexandra"),"issue-comment",&repo(),"Issue","alex",since()).is_none());}
#[test]fn sticky_notification_reason_is_not_an_event(){let mut v=comment("A later comment with no mention.");v["reason"]=json!("mention");assert!(filter::comment_mention(&v,"issue-comment",&repo(),"Issue","alex",since()).is_none());}
#[test]fn quoted_or_code_mentions_are_ignored(){for body in ["`@alex`","```rust\n// @alex\n```","> @alex, quoted", "someone@alex.example"]{assert!(!filter::mentions(body,"alex"));}}
#[test]fn edited_mentions_keep_stable_ids(){let a=filter::comment_mention(&comment("@alex, first"),"issue-comment",&repo(),"Issue","alex",since()).unwrap();let b=filter::comment_mention(&comment("@alex, edited"),"issue-comment",&repo(),"Issue","alex",since()).unwrap();assert_eq!(a.id,b.id);}
#[test]fn comment_namespaces_do_not_collide(){let c=comment("@alex");let a=filter::comment_mention(&c,"issue-comment",&repo(),"Issue","alex",since()).unwrap();let b=filter::comment_mention(&c,"review-comment",&repo(),"PR","alex",since()).unwrap();assert_ne!(a.id,b.id);}
#[test]fn no_untrusted_browser_links(){let mut c=comment("@alex");for url in ["file:///etc/passwd","https://github.com.evil.test/x","javascript:alert(1)","http://github.com/x","https://evil.test/"]{c["html_url"]=json!(url);assert!(filter::comment_mention(&c,"issue-comment",&repo(),"Issue","alex",since()).is_none());}}
#[test]fn api_subject_requires_matching_repository(){assert!(filter::subject_locator("https://api.github.com/repos/atelier/web/issues/1",&repo()).is_ok());for url in ["https://api.github.com/repos/other/web/issues/1","https://api.github.com/repos/atelier/web/issues/1/comments","https://api.github.com/repos/atelier/web/pulls/not-a-number","https://evil.test/repos/atelier/web/issues/1"]{assert!(filter::subject_locator(url,&repo()).is_err());}}
#[test]fn least_privilege_primary_scopes(){assert!(!validate_scopes(&["notifications".into()]).unwrap());assert!(validate_scopes(&["notifications".into(),"read:org".into()]).unwrap());for scope in ["repo","public_repo","gist","user","workflow","delete_repo","admin:org"]{assert!(validate_scopes(&["notifications".into(),scope.into()]).is_err());}assert!(validate_scopes(&[]).is_err());}

fn database()->anyhow::Result<(tempfile::TempDir,Store)>{let temp=tempfile::tempdir()?;let paths=Paths::at(temp.path().join("data"))?;let mut store=Store::open(&paths)?;store.save_config(&Config{login:"alex".into(),..Default::default()})?;Ok((temp,store))}
fn event()->Event{filter::review(&review(),&repo(),"PR","alex","alex",since()).unwrap()}
#[test]fn live_event_enters_durable_outbox()->anyhow::Result<()>{let(_temp,mut s)=database()?;assert_eq!(s.ingest("alex",&[event()],false)?,1);assert_eq!(s.outbox()?.len(),1);let ids=s.outbox()?.iter().map(|e|e.id.clone()).collect::<Vec<_>>();s.notified(&ids)?;assert!(s.outbox()?.is_empty());assert_eq!(s.ingest("alex",&[event()],false)?,0);Ok(())}
#[test]fn pause_does_not_generate_late_avalanche()->anyhow::Result<()>{let(_temp,mut s)=database()?;let mut c=s.config()?;c.paused_until=Utc::now().timestamp()+60;s.save_config(&c)?;s.ingest("alex",&[event()],false)?;assert_eq!(s.events()?.len(),1);assert!(s.outbox()?.is_empty());c.paused_until=0;s.save_config(&c)?;assert_eq!(s.ingest("alex",&[event()],false)?,0);Ok(())}
#[test]fn disabled_rule_is_not_replayed()->anyhow::Result<()>{let(_temp,mut s)=database()?;let mut c=s.config()?;c.rules.reviews=false;s.save_config(&c)?;s.ingest("alex",&[event()],false)?;assert!(s.events()?.is_empty());c.rules.reviews=true;s.save_config(&c)?;assert_eq!(s.ingest("alex",&[event()],false)?,0);Ok(())}
#[test]fn initial_cursor_is_quiet_then_overlaps()->anyhow::Result<()>{let(_temp,mut s)=database()?;assert!(s.cursor("notifications")?.1);let now=Utc::now();s.advance("alex","notifications",now)?;let(at,quiet)=s.cursor("notifications")?;assert!(!quiet);assert_eq!(at,now-Duration::minutes(2));Ok(())}
#[test]fn stale_account_cannot_advance_or_ingest()->anyhow::Result<()>{let(_temp,mut s)=database()?;s.disconnect()?;s.advance("alex","notifications",Utc::now())?;assert!(s.cursor("notifications")?.1);assert_eq!(s.ingest("alex",&[event()],false)?,0);Ok(())}
#[test]fn local_archive_is_reversible()->anyhow::Result<()>{let(_temp,mut s)=database()?;let e=event();s.ingest("alex",&[e.clone()],false)?;s.archive(&e.id,true)?;assert!(s.events()?[0].archived);assert!(!s.events()?[0].unread);s.archive(&e.id,false)?;assert!(!s.events()?[0].archived);Ok(())}
#[test]fn quiet_tasks_do_not_turn_into_old_banners()->anyhow::Result<()>{let(_temp,mut s)=database()?;let mut t=ThreadTask{id:"thread:1".into(),repository:repo(),subject_type:"PullRequest".into(),title:"PR".into(),subject_url:"https://api.github.com/repos/atelier/web/pulls/1".into(),latest_comment_url:None,reason:"review_requested".into(),since:Utc::now()-Duration::hours(24),quiet:true};s.enqueue("alex",&t)?;t.since=since();t.quiet=false;s.enqueue("alex",&t)?;let result=&s.tasks(1)?[0];assert!(!result.quiet);assert_eq!(result.since,t.since);Ok(())}
#[test]fn retention_caps_visible_history()->anyhow::Result<()>{let(_temp,mut s)=database()?;let values:Vec<_>=(0..510).map(|i|{let mut e=event();e.id=format!("review:{i}");e}).collect();s.ingest("alex",&values,true)?;assert_eq!(s.events()?.len(),500);Ok(())}
#[cfg(unix)]#[test]fn private_unix_directory_and_database()->anyhow::Result<()>{use std::os::unix::fs::PermissionsExt;let temp=tempfile::tempdir()?;let paths=Paths::at(temp.path().join("data"))?;let _s=Store::open(&paths)?;assert_eq!(std::fs::metadata(&paths.root)?.permissions().mode()&0o777,0o700);assert_eq!(std::fs::metadata(paths.db())?.permissions().mode()&0o777,0o600);Ok(())}
